name: collider_loading
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^15.2.4
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  flutter_gen: ^5.10.0
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/localization/
    - assets/fonts/
    - assets/images/
  fonts:
    - family: CourierPrime
      fonts:
        - asset: assets/fonts/CourierPrime-Regular.ttf
        - asset: assets/fonts/CourierPrime-Italic.ttf
        - asset: assets/fonts/CourierPrime-BoldItalic.ttf
        - asset: assets/fonts/CourierPrime-Bold.ttf

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
scripts:
generator: dart pub run build_runner build --delete-conflicting-outputs
  
